In [55]:
import pandas as pd

In [56]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [57]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [58]:
dataset=dataset.astype(float)

In [59]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [60]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [61]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                   1.0
1                   1.0
2                   1.0
3                   1.0
4                   1.0
..                  ...
394                 1.0
395                 1.0
396                 1.0
397                 1.0
398                 0.0

[399 rows x 1 columns]

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [63]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [64]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy'],'max_features': ['auto','sqrt','log2'],'splitter':['best','random']} 
grid = GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.93920665 0.97494195 0.93882893 0.95683048
        nan        nan 0.93875682 0.95708873 0.96078752 0.96077724]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [66]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)

In [67]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, grid_predictions)

In [68]:
from sklearn.metrics import classification_report
clf_report= classification_report(Y_test, grid_predictions)

In [69]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'random'}: 0.9420122887864824

In [70]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[43  2]
 [ 5 70]]

In [71]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

         0.0       0.90      0.96      0.92        45
         1.0       0.97      0.93      0.95        75

    accuracy                           0.94       120
   macro avg       0.93      0.94      0.94       120
weighted avg       0.94      0.94      0.94       120

In [72]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.9444444444444445

In [73]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001486,0.001984,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.002350,0.004341,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.004124,0.004836,0.029226,0.004829,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.929513,0.911105,0.964572,0.909115,0.981728,0.939207,0.029123,6
3,0.009035,0.005741,0.018526,0.007272,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982221,0.982221,0.982221,0.946153,0.981894,0.974942,0.014395,1
4,0.007589,0.006316,0.026894,0.004404,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.982221,0.909115,0.912029,0.964286,0.926494,0.938829,0.029272,7
5,0.006635,0.002039,0.025725,0.003413,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.964572,0.909115,0.964286,0.964286,0.981894,0.956830,0.024803,5
6,0.003194,0.004210,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.002112,0.003608,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.004729,0.003978,0.031714,0.009652,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.964286,0.892857,0.946663,0.945469,0.944509,0.938757,0.024080,8
9,0.006133,0.004006,0.023312,0.005688,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.964572,0.927778,0.929144,0.982221,0.981728,0.957089,0.024227,4
10,0.007076,0.006565,0.029064,0.006387,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.964572,0.982051,0.947015,0.928571,0.981728,0.960788,0.020652,2
11,0.008053,0.001894,0.025378,0.002735,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.928571,0.929144,0.982221,0.981728,0.960777,0.026063,3

In [74]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=int(input("SG_B:"))
sg_c_input=int(input("SG_C:"))
sg_d_input=int(input("SG_D:"))
sg_e_input=int(input("SG_E:"))
rbc_normal_input=int(input("RBC_NORMAL:"))
pc_normal_input=int(input("PC_NORMAL:"))
pcc_present_input=int(input("PCC_PRESENT:"))
ba_present_input=int(input("BA_PRESENT:"))
htn_yes_input=int(input("HTN_YES:"))
dm_yes_input=int(input("DM_YES:"))
cad_yes_input=int(input("CAD_YES:"))
appet_yes_input=int(input("APPET_YES:"))
pe_yes_input=int(input("PE_YES:"))
ane_yes_input=int(input("ANE_YES:"))

Age:36
BP:80
AL:3
SU:2
BGR:90
BU:52
SC:1.5
SOD:136
POT:4.
HRMO:14
PCV:45
WC:8000
RC:4.2
SG_B:2
SG_C:1
SG_D:1
SG_E:0
RBC_NORMAL:1
PC_NORMAL:1
PCC_PRESENT:0
BA_PRESENT:1
HTN_YES:1
DM_YES:0
CAD_YES:1
APPET_YES:1
PE_YES:0
ANE_YES:1

In [75]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,
                                 pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,
                                 pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,
                                 appet_yes_input,pe_yes_input,ane_yes_input,]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[0.]