In [3]:
import pandas as pd
import numpy as np

In [4]:
print(np.__version__)

1.24.3

In [6]:
dataset=pd.read_csv("CKD.csv")

In [7]:
dataset.head(250)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,60.0,70.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,140.000000,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,yes
246,60.0,90.000000,c,2.0,0.0,abnormal,normal,notpresent,notpresent,105.000000,...,33.000000,10500.000000,4.100000,no,no,no,yes,poor,no,yes
247,60.0,60.000000,c,3.0,1.0,normal,abnormal,present,notpresent,288.000000,...,25.000000,15200.000000,3.000000,yes,no,no,poor,poor,yes,yes
248,60.0,80.000000,a,0.0,2.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,yes,no,yes,poor,no,yes
249,60.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,261.000000,...,38.868902,4200.000000,3.400000,yes,no,no,yes,poor,no,yes

In [8]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [9]:
dataset=dataset.astype(float)

In [10]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [11]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [12]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                   1.0
1                   1.0
2                   1.0
3                   1.0
4                   1.0
..                  ...
394                 1.0
395                 1.0
396                 1.0
397                 1.0
398                 0.0

[399 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]} 
grid = GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
7 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.97164809 0.97143609 0.98198056 0.97859093
        nan        nan 0.97503791 0.97859093 0.98212445 0.97859093]
  warnings.warn(
C:\Anaconda\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [17]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, grid_predictions)

In [19]:
from sklearn.metrics import classification_report
clf_report= classification_report(Y_test, grid_predictions)

In [20]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 10}: 0.9834018801410106

In [21]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[45  0]
 [ 2 73]]

In [22]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

         0.0       0.96      1.00      0.98        45
         1.0       1.00      0.97      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

In [23]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.9997037037037036

In [24]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000000,0.000000,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000000,0.000000,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.029103,0.006651,0.011437,0.003751,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982221,0.982221,0.929513,0.964286,1.000000,0.971648,0.023904,7
3,0.212094,0.009545,0.023916,0.006793,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.963889,0.929513,0.982051,0.981728,0.971436,0.023871,8
4,0.019271,0.004676,0.016579,0.003680,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.963889,1.000000,0.964286,0.981728,0.981981,0.016062,2
5,0.233503,0.017620,0.024141,0.002016,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,3
6,0.000000,0.000000,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000494,0.000621,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.027172,0.003779,0.010707,0.001671,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,6
9,0.210899,0.005516,0.021106,0.004287,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,3
10,0.025209,0.002783,0.008291,0.003768,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.982051,0.964286,0.964286,1.000000,0.982124,0.015972,1
11,0.196774,0.008205,0.025398,0.006647,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,3

In [25]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=int(input("SG_B:"))
sg_c_input=int(input("SG_C:"))
sg_d_input=int(input("SG_D:"))
sg_e_input=int(input("SG_E:"))
rbc_normal_input=int(input("RBC_NORMAL:"))
pc_normal_input=int(input("PC_NORMAL:"))
pcc_present_input=int(input("PCC_PRESENT:"))
ba_present_input=int(input("BA_PRESENT:"))
htn_yes_input=int(input("HTN_YES:"))
dm_yes_input=int(input("DM_YES:"))
cad_yes_input=int(input("CAD_YES:"))
appet_yes_input=int(input("APPET_YES:"))
pe_yes_input=int(input("PE_YES:"))
ane_yes_input=int(input("ANE_YES:"))

Age:36
BP:80
AL:3
SU:2
BGR:90
BU:52
SC:1
SOD:136
POT:4
HRMO:13
PCV:40
WC:3000
RC:4
SG_B:1
SG_C:2
SG_D:1
SG_E:2
RBC_NORMAL:1
PC_NORMAL:0
PCC_PRESENT:1
BA_PRESENT:1
HTN_YES:0
DM_YES:1
CAD_YES:0
APPET_YES:1
PE_YES:1
ANE_YES:0

In [26]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,
                                 pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,
                                 pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,
                                 appet_yes_input,pe_yes_input,ane_yes_input,]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1.]